### ISSUE TITLE
Functions work but breaks website

### ISSUE THREAD

**Issue by thebencollection** [GamerGirlandCo/Songsterr-Plus-2.0#11]
The songster plus features work, but when searching and browsing the Songsterr website nothing loads until the extension is disabled.

**Comment by GamerGirlandCo** [comment]
will start working on this tomorrow!! (it's christmas here)

**Comment by GamerGirlandCo** [comment]
fixed in the latest release! 
thank you for bringing this to my attention :3

**Comment by thebencollection** [comment]
Thanks! Just tested and works great.
