### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by slavastra666** [GamerGirlandCo/Songsterr-Plus-2.0#13]
![image](https://user-images.githubusercontent.com/122186146/211175211-14b5789b-2861-425e-a52e-1e7c0d56c508.png)

**Comment by GamerGirlandCo** [comment]
try the latest release and let me know if it's still broken

**Comment by szymon-pitula** [comment]
Hi, yes the problem seems to persist with newest release aswell (tested on 28.01) :) 

EDIT: Well, I tested it on other tab, than the one that I loaded the extension with and there it did not work. When I load the page using the same page I used to load extension, I still get the message but it's all working smoothly :) Mby that could be a useful tip for troubleshooting section? 

Great job btw 👍

**Comment by GamerGirlandCo** [comment]
> Hi, yes the problem seems to persist with newest release aswell (tested on 28.01) :)
> 
> EDIT: Well, I tested it on other tab, than the one that I loaded the extension with and there it did not work. When I load the page using the same page I used to load extension, I still get the message but it's all working smoothly :) Mby that could be a useful tip for troubleshooting section?
> 
> Great job btw 👍

turns out the fuckers updated the code lol

anyways, expect a release with a fix in a few minutes!

**Comment by GamerGirlandCo** [comment]
@slavastra666 @szymon-pitula try this one out and let me know if it works! https://github.com/GamerGirlandCo/Songsterr-Plus-2.0/releases/tag/1.6.0

**Comment by slavastra666** [comment]
> try the latest release and let me know if it's still broken

You're The Best, it's working perfect!
thank you

**Comment by iamsxm** [comment]
not working again , web said Please disable your ad blocker and check network connection.
are those f**ker dont sleep just work 24 hours?

**Comment by GamerGirlandCo** [comment]
> not working again , web said Please disable your ad blocker and check network connection. are those f**ker dont sleep just work 24 hours?

lol
![image](https://user-images.githubusercontent.com/37163052/216739881-508fff07-7acc-462d-a7a9-a14bd19e6be8.png)

fix incoming btw :)

**Comment by GamerGirlandCo** [comment]
https://github.com/GamerGirlandCo/Songsterr-Plus-2.0/releases/tag/1.7.0
