### ISSUE TITLE
Not working again :((

### ISSUE THREAD

**Issue by ramazankzn** [GamerGirlandCo/Songsterr-Plus-2.0#14]
![image](https://user-images.githubusercontent.com/86193880/221184790-e19a11bc-1266-4959-abd2-54e8fc1ed6df.png)

**Comment by GamerGirlandCo** [comment]
download the latest release and let me know if it works! :)

**Comment by ramazankzn** [comment]
> download the latest release and let me know if it works! :)

Thanks. Now is perfect)
