### ISSUE TITLE
Doesn't support printing

### ISSUE THREAD

**Issue by ghost** [GamerGirlandCo/Songsterr-Plus-2.0#15]
Is there any way to help this boomer use ancient tech and print his tabs?

![image](https://user-images.githubusercontent.com/106550808/222902197-7eefd48e-f016-4ab7-9f3c-d9b2dcbe3393.png)

**Comment by ramazankzn** [comment]
I have same problem

**Comment by zarei-dev** [comment]
same here

**Comment by GamerGirlandCo** [comment]
just published a new release, it *should* work now. if not, let me know!

**Comment by agnardo** [comment]
It works just fine now. Thank you!

**Comment by ghost** [comment]
It works just fine now. Thank you!
