### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by Nikodemski** [GamerGirlandCo/Songsterr-Plus-2.0#17]
It worked earlier today, but when I used it a few minutes ago it didnt work. I read your instructions and install a new file but it still doesnt work. Pls help
![image](https://github.com/GamerGirlandCo/Songsterr-Plus-2.0/assets/77251455/59938b11-e479-4fad-84f5-69590ae88b8c)

**Comment by Olshan** [comment]
Same for me :(

**Comment by GamerGirlandCo** [comment]
let me know if the latest release fixes this :)

**Comment by stpafk** [comment]
not working here either :(

**Comment by GamerGirlandCo** [comment]
> not working here either :(

there's a new release, and it works on my end. please try that one!!

**Comment by stpafk** [comment]
> 

worked like a charm, thank you

**Comment by stpafk** [comment]
> > not working here either :(
> 
> there's a new release, and it works on my end. please try that one!!

worked like a charm, thank you

**Comment by Nikodemski** [comment]
Guys, new release works! Good job and thanks!!
