### ISSUE TITLE
Chrome support?

### ISSUE THREAD

**Issue by JopjeKnopje** [GamerGirlandCo/Songsterr-Plus-2.0#18]
Would it be possible to add support for chromium based browsers?

**Comment by mischief957** [comment]
I am wondering the same thing, chrome would be alot more useful for me.

**Comment by thehammergod** [comment]
Is it a feature or bug that I have to reload the .xpi everytime I open the
browser?

**Comment by mischief957** [comment]
For anyone on chrome looking for a working PLUS script here you go, worked perfect for me 

https://greasyfork.org/en/scripts/469079-songsterr-premium-songsterr-com

**Comment by GamerGirlandCo** [comment]
in the releases section, there's a .crx now!

however, it requires some extra steps:

1. load songsterr
2. click extension icon
3. hard reload the tab (ctrl+shift+R)
4. profit

you might want to pin the extension icon to the toolbar for easy access.

**Comment by MLGgamingpro** [comment]
you should probably close this issue since there is chrome support now
