### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by iamV1nger** [GamerGirlandCo/Songsterr-Plus-2.0#22]
Tabs just not open

![firefox_HiiW0FnUgO](https://github.com/GamerGirlandCo/Songsterr-Plus-2.0/assets/20910089/b56eef41-09a6-493a-b3e5-571e372a81d1)

**Comment by GamerGirlandCo** [comment]
@iamV1nger hey, could you download the latest release and tell me if it works?

**Comment by iamV1nger** [comment]
@GamerGirlandCo work thx, sorry for late reply
