### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by juliobguedes** [GamerGirlandCo/Songsterr-Plus-2.0#3]
Hey, is there any chance to allow printing?

**Comment by GamerGirlandCo** [comment]
hey! i've got it working on my end. test this and tell me if it works! if it does, i'll upload the release
[songsterr_plus_hack_2.0-1.1.3.zip](https://github.com/GamerGirlandCo/Songsterr-Plus-2.0/files/7945816/songsterr_plus_hack_2.0-1.1.3.zip)
