### ISSUE TITLE
Search Function Not working

### ISSUE THREAD

**Issue by JPHFanedits** [GamerGirlandCo/Songsterr-Plus-2.0#6]
I just installed this and I am unable to search for any tabs. It tells me to turn off my adblocker, which isn't on.

![image](https://user-images.githubusercontent.com/60670599/167193824-28cb721c-2f84-463f-8918-8744c9e6010c.png)

**Comment by GamerGirlandCo** [comment]
hi! i'm so sorry for only getting around to this now. i just published a release that fixes that. let me know if it works!! <sub>gosh i really need to be more careful, don't i..........</sub>

**Comment by GamerGirlandCo** [comment]
it looks like everything is working right (for now), so i'll just close this. feel free to reopen or submit a new issue if it happens again :>
