### ISSUE TITLE
Cannot load

### ISSUE THREAD

**Issue by Minhheo25** [GamerGirlandCo/Songsterr-Plus-2.0#7]
Hi, I applied your latest extension but this error come out.
![image](https://user-images.githubusercontent.com/109940378/180705416-7113bcf2-3937-44b3-ab05-ddca4e721a58.png)
Please help to fix it. Thank you!

**Comment by mefizto** [comment]
i confirm, same error

**Comment by Thomas-Manzoni** [comment]
Same error
