### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by X3oWyR** [GamerGirlandCo/Songsterr-Plus-2.0#8]
looks like they fixed it again. when i load the site it says failed to load and none of the features are working. also in firefox it says that the version of the extension is 1.2.1 even though i downloaded 1.3.1. probably forgot to change it?

**Comment by adras** [comment]
I just checked the sourcecode. Seems like the author forgot to update the version in the manifest file.

But I agree, besides the print function it seems like all other functions are not working. The icon also doesn't appear

**Comment by adras** [comment]
@X3oWyR Try [this one](https://github.com/adras/Songsterr-Plus-2.0)

**Comment by X3oWyR** [comment]
@adras great work! works like a charm

**Comment by adras** [comment]
@X3oWyR My version has a new button on the left side of the screen. Can you test it out? You can reply by creating an issue on my fork.
